name: CI - user app

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::905418475864:role/api-role
          aws-region: us-east-1

      - name: Login to ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push image
        run: |
          docker build -t 905418475864.dkr.ecr.us-east-1.amazonaws.com/live-youtube-api:${{ github.sha }} .
          docker push 905418475864.dkr.ecr.us-east-1.amazonaws.com/live-youtube-api:${{ github.sha }}

      - name: Deploy to App Runner Image
        id: deploy_apprunner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: app-runner-git-deploy-service
          image: ${{ steps.login_ecr.outputs.image }}
          access-role-arn: arn:aws:iam::905418475864:role/aws-service-role/apprunner.amazonaws.com/AWSServiceRoleForAppRunner
          region: us-east-1
          cpu: 1
          memory: 1

      - name: App Runner URL
        run: echo "App runner URL ${{ steps.deploy_apprunner.outputs.service-url }}"
